name: segan
channels:
  - conda-forge
  - anaconda
  - menpo
dependencies:
  - python=3.6
  - scipy=0.19.1
  - cudatoolkit=9
  - cudnn=7
  - wget
  - pip
  - pip:
    - cython
    - numpy==1.16
    - tensorflow_gpu==1.12.0
    - toml==0.9.2
